AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Location Functions for Passenger Proximity Chat

Transform: AWS::Serverless-2016-10-31

Parameters:
  MongoDbUri:
    Type: String
  DbName:
    Type: String
  JwtSecret:
    Type: String

Resources:
  UpdateUserLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/location/updateUserLocation.handler
      Runtime: nodejs18.x
      MemorySize: 256
      CodeUri: ../../
      Description: A Lambda function that updates user location.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  StackArn:
    Description: 'Location Functions Stack ARN'
    Value: !Ref AWS::StackId
