AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The backend of Passenger Proximity Chat

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'
    Runtime: nodejs18.x
    MemorySize: 256
    Timeout: 60
    Environment:
      Variables:
        MONGODB_URI: !Ref MongoDbUri
        DB_NAME: !Ref DbName
        JWT_SECRET: !Ref JwtSecret

Parameters:
  AppId:
    Type: String
  MongoDbUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /MongoDbUri
    Description: MongoDB connection URI
  DbName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /DbName
    Description: MongoDB Database name
  JwtSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /JwtSecret
    Description: JWT secret for token signing

Resources:
  UserFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api/user/user-functions.yml
      Parameters:
        MongoDbUri: !Ref MongoDbUri
        DbName: !Ref DbName
        JwtSecret: !Ref JwtSecret


  LocationFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api/location/location-functions.yml
      Parameters:
        MongoDbUri: !Ref MongoDbUri
        DbName: !Ref DbName
        JwtSecret: !Ref JwtSecret


Outputs:
  UserFunctionsStack:
    Description: 'User Functions Stack ARN'
    Value: !GetAtt UserFunctionsStack.Outputs.StackArn

  LocationFunctionsStack:
    Description: 'Location Functions Stack ARN'
    Value: !GetAtt LocationFunctionsStack.Outputs.StackArn
