AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The backend of Passenger Proximity Chat

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 60

Parameters:
  AppId:
    Type: String
  MongoDbUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /MongoDbUri
    Description: MongoDB connection URI
  DbName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /DbName
    Description: MongoDB Database name
  JwtSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /JwtSecret
    Description: JWT secret for token signing

Resources:
  # User functions
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/login.handler
      Description: A Lambda function that handles user login.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/signUp.handler
      Description: A Lambda function that handles user sign-up.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  VerifyTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/verifyToken.handler
      Description: A Lambda function that verifies JWT tokens.
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  GetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/getUserData.handler
      Description: A Lambda function that retrieves user data.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  LoginFunction:
    Description: 'Login Function ARN'
    Value: !GetAtt LoginFunction.Arn

  SignUpFunction:
    Description: 'SignUp Function ARN'
    Value: !GetAtt SignUpFunction.Arn

  VerifyTokenFunction:
    Description: 'VerifyToken Function ARN'
    Value: !GetAtt VerifyTokenFunction.Arn

  GetUserDataFunction:
    Description: 'GetUserData Function ARN'
    Value: !GetAtt GetUserDataFunction.Arn
