AWSTemplateFormatVersion: 2010-09-09
Description: >-
  User Functions for Passenger Proximity Chat

Transform: AWS::Serverless-2016-10-31

Parameters:
  MongoDbUri:
    Type: String
  DbName:
    Type: String
  JwtSecret:
    Type: String

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/user/login.handler
      Runtime: nodejs18.x
      CodeUri: ../../
      Description: A Lambda function that handles user login.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/user/signUp.handler
      Runtime: nodejs18.x
      CodeUri: ../../
      Description: A Lambda function that handles user sign-up.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  VerifyTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/user/verifyToken.handler
      Runtime: nodejs18.x
      CodeUri: ../../
      Description: A Lambda function that verifies JWT tokens.
      Environment:
        Variables:
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

  GetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/user/getUserData.handler
      Runtime: nodejs18.x
      CodeUri: ../../
      Description: A Lambda function that retrieves user data.
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
          DB_NAME: !Ref DbName
          JWT_SECRET: !Ref JwtSecret
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  StackArn:
    Description: 'User Functions Stack ARN'
    Value: !Ref AWS::StackId
