AWSTemplateFormatVersion: 2010-09-09
Description: >-
  User Functions for Passenger Proximity Chat

Transform: AWS::Serverless-2016-10-31

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/login.handler
      Description: A Lambda function that handles user login.
      Policies:
        - AWSLambdaBasicExecutionRole

  SignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/signUp.handler
      Description: A Lambda function that handles user sign-up.
      Policies:
        - AWSLambdaBasicExecutionRole

  VerifyTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/verifyToken.handler
      Description: A Lambda function that verifies JWT tokens.
      Policies:
        - AWSLambdaBasicExecutionRole

  GetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: api/user/getUserData.handler
      Description: A Lambda function that retrieves user data.
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  StackArn:
    Description: 'User Functions Stack ARN'
    Value: !Ref AWS::StackId
